using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace QuizPlatform.Migrations
{
    /// <inheritdoc />
    public partial class AddUserAuth : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Email"" character varying(255) NOT NULL,
                    ""PasswordHash"" character varying(500) NOT NULL,
                    ""Role"" integer NOT NULL,
                    ""Nickname"" character varying(50),
                    ""Gender"" character varying(20),
                    ""Status"" character varying(200),
                    ""CreatedAt"" timestamp with time zone NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Exams"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Title"" character varying(500) NOT NULL,
                    ""Description"" character varying(2000),
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW())
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Questions"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ExamId"" integer NOT NULL,
                    ""QuestionText"" text NOT NULL,
                    ""OptionA"" character varying(1000) NOT NULL,
                    ""OptionB"" character varying(1000) NOT NULL,
                    ""OptionC"" character varying(1000) NOT NULL,
                    ""OptionD"" character varying(1000) NOT NULL,
                    ""CorrectAnswer"" character varying(1) NOT NULL,
                    CONSTRAINT ""FK_Questions_Exams_ExamId"" FOREIGN KEY (""ExamId"") REFERENCES ""Exams"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Exams"" ADD COLUMN IF NOT EXISTS ""CreatedById"" integer;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Exams_Users_CreatedById') THEN
                        ALTER TABLE ""Exams"" ADD CONSTRAINT ""FK_Exams_Users_CreatedById"" FOREIGN KEY (""CreatedById"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Exams_CreatedById"" ON ""Exams"" (""CreatedById"");
                CREATE INDEX IF NOT EXISTS ""IX_Questions_ExamId"" ON ""Questions"" (""ExamId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Questions");

            migrationBuilder.DropTable(
                name: "Exams");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
